name: publish-fdsx-ui

on:
  push:
    tags:
      - "fdsx-ui-v*"
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    name: publish-to-npm
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/fdsx-ui
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: packages/fdsx-ui
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: print npm version
        run: npm --version

      - name: install
        run: npm ci

      - name: audit signatures
        run: npm audit signatures

      - name: typecheck
        run: npm run typecheck

      - name: test
        run: npm test

      - name: build
        run: npm run build

      - name: verify tarball contents
        run: npm pack --dry-run

      - name: publish
        run: npm publish
